baseURL = 'https://asorbus.github.io/'
title = 'Reflexionen'
author = "ASANUMA Kouki"
copyright = "Copyright © 2009–2024, ASANUMA Kouki; all rights reserved."
paginate = 5
languageCode = "ja"
DefaultContentLanguage = "ja"

googleAnalytics = "G-379G9T9FKD"

[params]
  color = 'wheat' 

  twitter = 'asorbus'
  github = 'asorbus'
  rss = true  

  avatar = 'asanuma.kouki@gmail.com'
  name = 'ASANUMA Kouki'
  bio = 'asorbus'

  disableHLJS = true 
  disablePostNavigation = false
  monoDarkIcon = false 
  math = false 

[menu]

  [[menu.main]]
    identifier = "info"
    name = "info ℹ"
    url = "/info/"
    weight = 10

[taxonomies]
tag = "tags"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
